classdef MX_Poly6
    properties
        T;
        P0;
        V0;
        A0;
        Pm;
        P1;
        V1;
        A1;
        S;
    end
    
    methods
        function obj = MX_Poly6(t, p0, v0, a0, pm, p1, v1, a1)
            obj.T  = t;
            obj.P0 = p0;
            obj.V0 = v0;
            obj.A0 = a0;
            obj.Pm = pm;
            obj.P1 = p1;
            obj.V1 = v1;
            obj.A1 = a1;
            [S.a,S.b,S.c,S.d,S.e,S.f,S.g] = autoGen_sixOrderPolyCoeff(t, p0, v0, a0, pm, p1, v1, a1);
            obj.S = S;
        end
        
        function [pos, vel, acc] = getSixOrderPoly(obj, s)
            a = obj.S.a;
            b = obj.S.b;
            c = obj.S.c;
            d = obj.S.d;
            e = obj.S.e;
            f = obj.S.f;
            g = obj.S.g;
            
            t = s * obj.T;

            pos = a + b .* t +  c .* t.^2 +     d .* t.^3 +      e .* t.^4 +      f .* t.^5 +      g .* t.^6;
            vel =          b + 2 * c .* t + 3 * d .* t.^2 +  4 * e .* t.^3 +  5 * f .* t.^4 +  6 * g .* t.^5;
            acc =                  2 * c  +    6 * d .* t + 12 * e .* t.^2 + 20 * f .* t.^3 + 30 * g .* t.^4;
        end        
    end 
 
end

function [a,b,c,d,e,f,g] = autoGen_sixOrderPolyCoeff(T,p0,v0,a0,pm,p1,v1,a1)
%AUTOGEN_SIXORDERPOLYCOEFF
%    [A,B,C,D,E,F,G] = AUTOGEN_SIXORDERPOLYCOEFF(T,P0,V0,A0,PM,P1,V1,A1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Nov-2021 17:19:40

a = p0;
if nargout > 1
    b = v0;
end
if nargout > 2
    c = a0./2.0;
end
if nargout > 3
    t2 = T.^2;
    t4 = pm.*3.84e+2;
    t3 = a1.*t2;
    d = 1.0./T.^3.*(p0.*8.4e+1+p1.*4.4e+1-pm.*1.28e+2+t3+T.*v0.*3.2e+1-T.*v1.*1.2e+1+a0.*t2.*5.0).*(-1.0./2.0);
end
if nargout > 4
    t5 = -t4;
    e = (1.0./t2.^2.*(p0.*2.22e+2+p1.*1.62e+2+t3.*4.0+t5+T.*v0.*7.6e+1-T.*v1.*4.6e+1+a0.*t2.*9.0))./2.0;
end
if nargout > 5
    f = 1.0./T.^5.*(p0.*2.04e+2+p1.*1.8e+2+t3.*5.0+t5+T.*v0.*6.6e+1-T.*v1.*5.4e+1+a0.*t2.*7.0).*(-1.0./2.0);
end
if nargout > 6
    g = 1.0./t2.^3.*(p0.*3.2e+1+p1.*3.2e+1-pm.*6.4e+1+t3+T.*v0.*1.0e+1-T.*v1.*1.0e+1+a0.*t2);
end

end