classdef MX_Poly5
    properties
        T;
        P0;
        V0;
        A0;
        P1;
        V1;
        A1;
        S;
    end
    
    methods
        function obj = MX_Poly5(t, p0, v0, a0, p1, v1, a1)
            obj.T  = t;
            obj.P0 = p0;
            obj.V0 = v0;
            obj.A0 = a0;
            obj.P1 = p1;
            obj.V1 = v1;
            obj.A1 = a1;
            [S.a,S.b,S.c,S.d,S.e,S.f] = autoGen_fiveOrderPolyCoeff(t, p0, v0, a0, p1, v1, a1);
            obj.S = S;
        end
        
        function [pos, vel, acc] = getFiveOrderPoly(obj, s)
            a = obj.S.a;
            b = obj.S.b;
            c = obj.S.c;
            d = obj.S.d;
            e = obj.S.e;
            f = obj.S.f;
            
            t = s * obj.T;

            pos = a + b .* t +  c .* t.^2 +     d .* t.^3 +      e .* t.^4 +      f .* t.^5;
            vel =          b + 2 * c .* t + 3 * d .* t.^2 +  4 * e .* t.^3 +  5 * f .* t.^4;
            acc =                  2 * c  +    6 * d .* t + 12 * e .* t.^2 + 20 * f .* t.^3;
        end        
    end 
 
end

function [a,b,c,d,e,f] = autoGen_fiveOrderPolyCoeff(T,p0,v0,a0,p1,v1,a1)
%AUTOGEN_FIVEORDERPOLYCOEFF
%    [A,B,C,D,E,F] = AUTOGEN_FIVEORDERPOLYCOEFF(T,P0,V0,A0,P1,V1,A1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Apr-2022 15:00:49

a = p0;
if nargout > 1
    b = v0;
end
if nargout > 2
    c = a0./2.0;
end
if nargout > 3
    t2 = T.^2;
    t3 = a1.*t2;
    t4 = a0.*t2.*3.0;
    t5 = -t3;
    d = 1.0./T.^3.*(p0.*2.0e+1-p1.*2.0e+1+t4+t5+T.*v0.*1.2e+1+T.*v1.*8.0).*(-1.0./2.0);
end
if nargout > 4
    e = (1.0./t2.^2.*(p0.*3.0e+1-p1.*3.0e+1-t3.*2.0+t4+T.*v0.*1.6e+1+T.*v1.*1.4e+1))./2.0;
end
if nargout > 5
    f = 1.0./T.^5.*(p0.*1.2e+1-p1.*1.2e+1+t5+T.*v0.*6.0+T.*v1.*6.0+a0.*t2).*(-1.0./2.0);
end

end